// <auto-generated />
using GemApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gem.Api.Migrations
{
    [DbContext(typeof(GemDbContext))]
    partial class GemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GemApi.Models.EscolaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.ToTable("EscolaItens");
                });

            modelBuilder.Entity("GemApi.Models.IgrejaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<bool>("Status");

                    b.HasKey("Id");

                    b.ToTable("IgrejaItens");
                });
#pragma warning restore 612, 618
        }
    }
}
